services:
  frontend:
    build:
      context: ./elastic-eats-ui  # React project folder
    ports:
      - "5173:5173"  # Map Vite's dev server port
    environment:
      NODE_VERSION: 20.12.2  # Node.js version
      NPM_VERSION: 10.5.0    # npm version
    restart: always