services:
  frontend:
    build:
      context: ./elastic-eats-ui
    ports:
      - "5173:5173"
    environment:
      NODE_VERSION: 20.12.2
      NPM_VERSION: 10.5.0
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./elastic-eats-ui:/app
      - /app/node_modules
    restart: always
    networks:
      - app-network
    command: ["npm", "run", "dev"]

  app:
    build:
      context: .
    container_name: python_app
    ports:
      - "5001:5001"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - RECIPE_API_KEY=${RECIPE_API_KEY}  
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    networks:
      - app-network
    #entrypoint: ["/app/wait-for-elasticsearch.sh"]
    command: ["python", "server/server.py", "runserver", "0.0.0.0:5001"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true  
      - xpack.security.authc.apiKey.enabled=true
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PW}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_config:/usr/share/elasticsearch/config  
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 | grep -q 'cluster_name'"]
      interval: 10s
      timeout: 10s
      retries: 30

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  
      - ELASTICSEARCH_SERVICE_TOKEN=${ELASTICSEARCH_TOKEN}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml  
    networks:
      - app-network

volumes:
  es_data:
    driver: local
  es_config:
    driver: local

networks:
    app-network:
      driver: bridge
